'use client';

import type { Metadata } from "next";
import localFont from "next/font/local";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

const assa = localFont({
  src: "./fonts/AssacomFreeGothic.ttf",
  variable: "--assa",
  weight: "100",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={assa.className}
      >
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
